/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAgentIdRouteImport } from './routes/dashboard/$agentId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as DashboardAgentIdSitemapRouteImport } from './routes/dashboard/$agentId.sitemap'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAgentIdRoute = DashboardAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAgentIdSitemapRoute = DashboardAgentIdSitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => DashboardAgentIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/$agentId': typeof DashboardAgentIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$agentId/sitemap': typeof DashboardAgentIdSitemapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/$agentId': typeof DashboardAgentIdRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$agentId/sitemap': typeof DashboardAgentIdSitemapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/$agentId': typeof DashboardAgentIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$agentId/sitemap': typeof DashboardAgentIdSitemapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/health'
    | '/auth/callback'
    | '/dashboard/$agentId'
    | '/dashboard/'
    | '/dashboard/$agentId/sitemap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/health'
    | '/auth/callback'
    | '/dashboard/$agentId'
    | '/dashboard'
    | '/dashboard/$agentId/sitemap'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/health'
    | '/auth/callback'
    | '/dashboard/$agentId'
    | '/dashboard/'
    | '/dashboard/$agentId/sitemap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/$agentId': {
      id: '/dashboard/$agentId'
      path: '/$agentId'
      fullPath: '/dashboard/$agentId'
      preLoaderRoute: typeof DashboardAgentIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$agentId/sitemap': {
      id: '/dashboard/$agentId/sitemap'
      path: '/sitemap'
      fullPath: '/dashboard/$agentId/sitemap'
      preLoaderRoute: typeof DashboardAgentIdSitemapRouteImport
      parentRoute: typeof DashboardAgentIdRoute
    }
  }
}

interface DashboardAgentIdRouteChildren {
  DashboardAgentIdSitemapRoute: typeof DashboardAgentIdSitemapRoute
}

const DashboardAgentIdRouteChildren: DashboardAgentIdRouteChildren = {
  DashboardAgentIdSitemapRoute: DashboardAgentIdSitemapRoute,
}

const DashboardAgentIdRouteWithChildren =
  DashboardAgentIdRoute._addFileChildren(DashboardAgentIdRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAgentIdRoute: typeof DashboardAgentIdRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAgentIdRoute: DashboardAgentIdRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
